services:
  projectbase:
    build: .
    container_name: projectbase
    restart: unless-stopped
    ports:
      - "${PROJECTBASE_PORT:-8120}:8120"
    volumes:
      - ./app/pb_data:/app/app/pb_data
      - ./app/pb_public:/app/app/pb_public
      - ./app/pb_hooks:/app/app/pb_hooks
      - ./app/pb_migrations:/app/app/pb_migrations
    environment:
      - PROJECTBASE_PORT=8120
      - PROJECTBASE_HOST=0.0.0.0
