#!/usr/bin/env python3
"""Sweep test-fixture issues out of a ProjectBase instance.

The dogfooded ProjectBase instance doubles as the pytest target (see
AGENTS.md). Fixture records that tests create and forget to delete pollute
the backlog: `test_export_json_round_trips_custom_fields` alone leaked 147
"Export CustomFields <uid>" issues before this script existed. This utility
finds records matching the canonical test-fixture title prefixes and
(optionally) deletes them, so a human reading the board sees real work, not
automated junk.

The prefix list lives HERE so every consumer shares one source of truth:
  - tests/test_api.py session cleanup deletes these after each run
  - tests/test_fixture_hygiene.py asserts zero remain (drift guard)

Usage:
  python3 scripts/cleanup-test-fixtures.py             # dry-run: report only
  python3 scripts/cleanup-test-fixtures.py --apply     # delete matches
  python3 scripts/cleanup-test-fixtures.py --json      # machine-readable
  python3 scripts/cleanup-test-fixtures.py --backup /tmp/fixture-backup.json

Environment:
  PROJECTBASE_URL        default http://127.0.0.1:8120
  PB_SUPERUSER_EMAIL     default f@flow.com
  PB_SUPERUSER_PASSWORD  default superdev123
"""

import argparse
import json
import os
import re
import sys
import urllib.error
import urllib.request
import uuid

BASE_URL = os.environ.get("PROJECTBASE_URL", "http://127.0.0.1:8120")
SUPERUSER_EMAIL = os.environ.get("PB_SUPERUSER_EMAIL", "f@flow.com")
SUPERUSER_PASSWORD = os.environ.get("PB_SUPERUSER_PASSWORD", "superdev123")

# Canonical test-fixture title prefixes. Every one of these is a unique-uid
# title generated by a test in tests/test_api.py (or a sibling suite); no
# human-created issue legitimately uses them. Keep this list in sync with the
# tests that create fixtures.
FIXTURE_TITLE_PREFIXES = (
    "Export CustomFields ",
    "Export Fixture ",
    "Search Identifier Probe ",
    # test_importer_source_key_dedup_cross_request creates "Keyed A <uid>"
    # and "Keyed B <uid>" (a bare "Keyed " prefix would match neither shape).
    "Keyed A ",
    "Keyed B ",
)

# The uid suffix is _uid() = uuid.uuid4().hex[:10] in tests/test_api.py.
# Matching ONLY a hex suffix (8-40 chars) prevents sweeping a human title that
# merely starts with the same words (e.g. "Export CustomFields is a feature").
_FIXTURE_UID_RE = re.compile(r"[0-9a-f]{8,40}\Z")

_PAGE_SIZE = 200


def _request(method, path, body=None, token=None, timeout=20):
    url = f"{BASE_URL}{path}"
    data = None
    headers = {"Content-Type": "application/json"}
    if token:
        headers["Authorization"] = token
    if body is not None:
        data = json.dumps(body).encode()
    req = urllib.request.Request(url, data=data, headers=headers, method=method)
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            raw = resp.read().decode(errors="replace")
            status = resp.status
    except urllib.error.HTTPError as err:
        raw = err.read().decode(errors="replace")
        status = err.code
    except urllib.error.URLError as err:
        raise SystemExit(
            f"cannot reach ProjectBase at {BASE_URL}: {err.reason}"
        ) from err
    try:
        return status, json.loads(raw)
    except json.JSONDecodeError:
        return status, raw


def _superuser_token():
    status, body = _request(
        "POST",
        "/api/collections/_superusers/auth-with-password",
        {"identity": SUPERUSER_EMAIL, "password": SUPERUSER_PASSWORD},
    )
    if status != 200:
        raise SystemExit(f"superuser auth failed ({status}): {body}")
    return body["token"]


def _is_fixture(record):
    title = record.get("title") or ""
    for prefix in FIXTURE_TITLE_PREFIXES:
        if title.startswith(prefix) and _FIXTURE_UID_RE.fullmatch(title[len(prefix):]):
            return True
    return False


def find_fixtures(token):
    """Walk every page of issues and return records matching the prefixes."""
    matches = []
    for page in range(1, 200):
        status, body = _request(
            "GET",
            f"/api/collections/issues/records?perPage={_PAGE_SIZE}"
            f"&sort=-created&page={page}",
            token=token,
        )
        if status != 200:
            raise SystemExit(f"listing issues failed ({status}): {body}")
        items = body.get("items") or []
        if not items:
            break
        matches.extend(it for it in items if _is_fixture(it))
        if len(items) < _PAGE_SIZE:
            break
    return matches


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--apply", action="store_true",
                        help="delete matching records (default is dry-run)")
    parser.add_argument("--json", action="store_true",
                        help="emit machine-readable JSON to stdout")
    parser.add_argument("--backup", metavar="PATH", default=None,
                        help="write matched records to PATH before deleting")
    args = parser.parse_args(argv)

    token = _superuser_token()
    matches = find_fixtures(token)
    deleted = 0

    if matches and (args.apply or args.backup):
        backup_path = args.backup or (
            f"/tmp/projectbase-fixture-sweep-{uuid.uuid4().hex[:12]}.json"
        )
        with open(backup_path, "w", encoding="utf-8") as fh:
            json.dump(
                [{"id": m["id"], "identifier": m.get("identifier"),
                  "title": m.get("title"), "project": m.get("project")}
                 for m in matches],
                fh, indent=2,
            )
        if not args.json:
            print(f"backup written: {backup_path}")

    if args.apply:
        for m in matches:
            status, _ = _request(
                "DELETE", f"/api/collections/issues/records/{m['id']}", token=token
            )
            if 200 <= status < 300:
                deleted += 1
            elif not args.json:
                print(f"delete failed ({status}) for {m.get('identifier')}: {m['id']}")

    if args.json:
        print(json.dumps({
            "matches": len(matches),
            "deleted": deleted,
            "prefixes": list(FIXTURE_TITLE_PREFIXES),
            "dry_run": not args.apply,
            "url": BASE_URL,
        }))
        return

    print(f"matches: {len(matches)}  deleted: {deleted}  "
          f"(mode: {'apply' if args.apply else 'dry-run'})")
    for m in matches:
        print(f"  {m.get('identifier')} :: {m.get('title')}")


if __name__ == "__main__":
    main()
